config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "dashboards#show"

  get '/sign_up', to: 'users#new', as: 'new_user'
  post '/users', to: 'users#create'
  get '/users/:id', to: 'users#show', as: 'user'

  resources :trips do
    resources :flights
    resources :receipts, only: [:index, :new, :create]
    resources :travelgroupings, only: [:new, :create]
  end

  get "/login", to: "sessions#new"
  post "/sessions", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
  get "/users/:id/dashboards", to: "dashboards#show", as: 'user_dashboard'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TravelProRails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
     <nav>
        <ul>
          <li><%= link_to "Home", root_path %></li>
         <% if logged_in? %>
          <li><%= link_to "Create Trip", new_trip_path %></li>
          <li><%= link_to"#{current_user.first_name}", user_path(current_user) %></li>
        <% end %>
        </ul>
        <% if logged_in? %>
          <button class="button"><%= link_to "Logout", logout_path, method: :delete %></button>
        <% else %>
          <button class="button"><%= link_to "Register", new_user_path %></button>
          <button class="button"><%= link_to "Login", login_path %></button>
        <% end %>
    </nav>
    <h1>Travel Pro</h1>
    <%= yield %>
  </body>
  <footer>© Designed & Developed by Baska Batbold.</footer>

</html>